version: '3'

services:
  
  api:
    container_name: flask_api
    restart: always
    build: ./api
    volumes: ['./api:/api']
    networks:
      - mysql-compose-network
    expose:
      - "5000"
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'processor_image'
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/my-db

    networks: 
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network
volumes:
  my-db:



networks:
  mysql-compose-network:
    driver: bridge